name: ni_visa_dart
description: NI VISA Library for Dart.
version: 0.1.0
repository: https://github.com/djbird2046/ni_visa_dart

environment:
  sdk: ^3.4.3

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
