// This file is auto-generated by ffigen. Do not edit.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// NI VISA Library for Dart via FFI.
class NIVisaFFI {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NIVisaFFI(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NIVisaFFI.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup) : _lookup = lookup;

  int viOpenDefaultRM(
    ViPSession vi,
  ) {
    return _viOpenDefaultRM(
      vi,
    );
  }

  late final _viOpenDefaultRMPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViPSession)>>('viOpenDefaultRM');
  late final _viOpenDefaultRM = _viOpenDefaultRMPtr.asFunction<int Function(ViPSession)>();

  int viFindRsrc(
    int sesn,
    ViConstString expr,
    ViPFindList vi,
    ViPUInt32 retCnt,
    ffi.Pointer<ViChar> desc,
  ) {
    return _viFindRsrc(
      sesn,
      expr,
      vi,
      retCnt,
      desc,
    );
  }

  late final _viFindRsrcPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString, ViPFindList, ViPUInt32, ffi.Pointer<ViChar>)>>('viFindRsrc');
  late final _viFindRsrc = _viFindRsrcPtr.asFunction<int Function(int, ViConstString, ViPFindList, ViPUInt32, ffi.Pointer<ViChar>)>();

  int viFindNext(
    int vi,
    ffi.Pointer<ViChar> desc,
  ) {
    return _viFindNext(
      vi,
      desc,
    );
  }

  late final _viFindNextPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViFindList, ffi.Pointer<ViChar>)>>('viFindNext');
  late final _viFindNext = _viFindNextPtr.asFunction<int Function(int, ffi.Pointer<ViChar>)>();

  int viParseRsrc(
    int rmSesn,
    ViConstRsrc rsrcName,
    ViPUInt16 intfType,
    ViPUInt16 intfNum,
  ) {
    return _viParseRsrc(
      rmSesn,
      rsrcName,
      intfType,
      intfNum,
    );
  }

  late final _viParseRsrcPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstRsrc, ViPUInt16, ViPUInt16)>>('viParseRsrc');
  late final _viParseRsrc = _viParseRsrcPtr.asFunction<int Function(int, ViConstRsrc, ViPUInt16, ViPUInt16)>();

  int viParseRsrcEx(
    int rmSesn,
    ViConstRsrc rsrcName,
    ViPUInt16 intfType,
    ViPUInt16 intfNum,
    ffi.Pointer<ViChar> rsrcClass,
    ffi.Pointer<ViChar> expandedUnaliasedName,
    ffi.Pointer<ViChar> aliasIfExists,
  ) {
    return _viParseRsrcEx(
      rmSesn,
      rsrcName,
      intfType,
      intfNum,
      rsrcClass,
      expandedUnaliasedName,
      aliasIfExists,
    );
  }

  late final _viParseRsrcExPtr =
      _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstRsrc, ViPUInt16, ViPUInt16, ffi.Pointer<ViChar>, ffi.Pointer<ViChar>, ffi.Pointer<ViChar>)>>('viParseRsrcEx');
  late final _viParseRsrcEx = _viParseRsrcExPtr.asFunction<int Function(int, ViConstRsrc, ViPUInt16, ViPUInt16, ffi.Pointer<ViChar>, ffi.Pointer<ViChar>, ffi.Pointer<ViChar>)>();

  int viOpen(
    int sesn,
    ViConstRsrc name,
    int mode,
    int timeout,
    ViPSession vi,
  ) {
    return _viOpen(
      sesn,
      name,
      mode,
      timeout,
      vi,
    );
  }

  late final _viOpenPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstRsrc, ViAccessMode, ViUInt32, ViPSession)>>('viOpen');
  late final _viOpen = _viOpenPtr.asFunction<int Function(int, ViConstRsrc, int, int, ViPSession)>();

  int viClose(
    int vi,
  ) {
    return _viClose(
      vi,
    );
  }

  late final _viClosePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViObject)>>('viClose');
  late final _viClose = _viClosePtr.asFunction<int Function(int)>();

  int viSetAttribute(
    int vi,
    int attrName,
    int attrValue,
  ) {
    return _viSetAttribute(
      vi,
      attrName,
      attrValue,
    );
  }

  late final _viSetAttributePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViObject, ViAttr, ViAttrState)>>('viSetAttribute');
  late final _viSetAttribute = _viSetAttributePtr.asFunction<int Function(int, int, int)>();

  int viGetAttribute(
    int vi,
    int attrName,
    ffi.Pointer<ffi.Void> attrValue,
  ) {
    return _viGetAttribute(
      vi,
      attrName,
      attrValue,
    );
  }

  late final _viGetAttributePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViObject, ViAttr, ffi.Pointer<ffi.Void>)>>('viGetAttribute');
  late final _viGetAttribute = _viGetAttributePtr.asFunction<int Function(int, int, ffi.Pointer<ffi.Void>)>();

  int viStatusDesc(
    int vi,
    int status,
    ffi.Pointer<ViChar> desc,
  ) {
    return _viStatusDesc(
      vi,
      status,
      desc,
    );
  }

  late final _viStatusDescPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViObject, ViStatus, ffi.Pointer<ViChar>)>>('viStatusDesc');
  late final _viStatusDesc = _viStatusDescPtr.asFunction<int Function(int, int, ffi.Pointer<ViChar>)>();

  int viTerminate(
    int vi,
    int degree,
    int jobId,
  ) {
    return _viTerminate(
      vi,
      degree,
      jobId,
    );
  }

  late final _viTerminatePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViObject, ViUInt16, ViJobId)>>('viTerminate');
  late final _viTerminate = _viTerminatePtr.asFunction<int Function(int, int, int)>();

  int viLock(
    int vi,
    int lockType,
    int timeout,
    ViConstKeyId requestedKey,
    ffi.Pointer<ViChar> accessKey,
  ) {
    return _viLock(
      vi,
      lockType,
      timeout,
      requestedKey,
      accessKey,
    );
  }

  late final _viLockPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViAccessMode, ViUInt32, ViConstKeyId, ffi.Pointer<ViChar>)>>('viLock');
  late final _viLock = _viLockPtr.asFunction<int Function(int, int, int, ViConstKeyId, ffi.Pointer<ViChar>)>();

  int viUnlock(
    int vi,
  ) {
    return _viUnlock(
      vi,
    );
  }

  late final _viUnlockPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession)>>('viUnlock');
  late final _viUnlock = _viUnlockPtr.asFunction<int Function(int)>();

  int viEnableEvent(
    int vi,
    int eventType,
    int mechanism,
    int context,
  ) {
    return _viEnableEvent(
      vi,
      eventType,
      mechanism,
      context,
    );
  }

  late final _viEnableEventPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViEventType, ViUInt16, ViEventFilter)>>('viEnableEvent');
  late final _viEnableEvent = _viEnableEventPtr.asFunction<int Function(int, int, int, int)>();

  int viDisableEvent(
    int vi,
    int eventType,
    int mechanism,
  ) {
    return _viDisableEvent(
      vi,
      eventType,
      mechanism,
    );
  }

  late final _viDisableEventPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViEventType, ViUInt16)>>('viDisableEvent');
  late final _viDisableEvent = _viDisableEventPtr.asFunction<int Function(int, int, int)>();

  int viDiscardEvents(
    int vi,
    int eventType,
    int mechanism,
  ) {
    return _viDiscardEvents(
      vi,
      eventType,
      mechanism,
    );
  }

  late final _viDiscardEventsPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViEventType, ViUInt16)>>('viDiscardEvents');
  late final _viDiscardEvents = _viDiscardEventsPtr.asFunction<int Function(int, int, int)>();

  int viWaitOnEvent(
    int vi,
    int inEventType,
    int timeout,
    ViPEventType outEventType,
    ViPEvent outContext,
  ) {
    return _viWaitOnEvent(
      vi,
      inEventType,
      timeout,
      outEventType,
      outContext,
    );
  }

  late final _viWaitOnEventPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViEventType, ViUInt32, ViPEventType, ViPEvent)>>('viWaitOnEvent');
  late final _viWaitOnEvent = _viWaitOnEventPtr.asFunction<int Function(int, int, int, ViPEventType, ViPEvent)>();

  int viInstallHandler(
    int vi,
    int eventType,
    ViHndlr handler,
    ViAddr userHandle,
  ) {
    return _viInstallHandler(
      vi,
      eventType,
      handler,
      userHandle,
    );
  }

  late final _viInstallHandlerPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViEventType, ViHndlr, ViAddr)>>('viInstallHandler');
  late final _viInstallHandler = _viInstallHandlerPtr.asFunction<int Function(int, int, ViHndlr, ViAddr)>();

  int viUninstallHandler(
    int vi,
    int eventType,
    ViHndlr handler,
    ViAddr userHandle,
  ) {
    return _viUninstallHandler(
      vi,
      eventType,
      handler,
      userHandle,
    );
  }

  late final _viUninstallHandlerPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViEventType, ViHndlr, ViAddr)>>('viUninstallHandler');
  late final _viUninstallHandler = _viUninstallHandlerPtr.asFunction<int Function(int, int, ViHndlr, ViAddr)>();

  int viRead(
    int vi,
    ViPBuf buf,
    int cnt,
    ViPUInt32 retCnt,
  ) {
    return _viRead(
      vi,
      buf,
      cnt,
      retCnt,
    );
  }

  late final _viReadPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViPBuf, ViUInt32, ViPUInt32)>>('viRead');
  late final _viRead = _viReadPtr.asFunction<int Function(int, ViPBuf, int, ViPUInt32)>();

  int viReadAsync(
    int vi,
    ViPBuf buf,
    int cnt,
    ViPJobId jobId,
  ) {
    return _viReadAsync(
      vi,
      buf,
      cnt,
      jobId,
    );
  }

  late final _viReadAsyncPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViPBuf, ViUInt32, ViPJobId)>>('viReadAsync');
  late final _viReadAsync = _viReadAsyncPtr.asFunction<int Function(int, ViPBuf, int, ViPJobId)>();

  int viReadToFile(
    int vi,
    ViConstString filename,
    int cnt,
    ViPUInt32 retCnt,
  ) {
    return _viReadToFile(
      vi,
      filename,
      cnt,
      retCnt,
    );
  }

  late final _viReadToFilePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString, ViUInt32, ViPUInt32)>>('viReadToFile');
  late final _viReadToFile = _viReadToFilePtr.asFunction<int Function(int, ViConstString, int, ViPUInt32)>();

  int viWrite(
    int vi,
    ViConstBuf buf,
    int cnt,
    ViPUInt32 retCnt,
  ) {
    return _viWrite(
      vi,
      buf,
      cnt,
      retCnt,
    );
  }

  late final _viWritePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstBuf, ViUInt32, ViPUInt32)>>('viWrite');
  late final _viWrite = _viWritePtr.asFunction<int Function(int, ViConstBuf, int, ViPUInt32)>();

  int viWriteAsync(
    int vi,
    ViConstBuf buf,
    int cnt,
    ViPJobId jobId,
  ) {
    return _viWriteAsync(
      vi,
      buf,
      cnt,
      jobId,
    );
  }

  late final _viWriteAsyncPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstBuf, ViUInt32, ViPJobId)>>('viWriteAsync');
  late final _viWriteAsync = _viWriteAsyncPtr.asFunction<int Function(int, ViConstBuf, int, ViPJobId)>();

  int viWriteFromFile(
    int vi,
    ViConstString filename,
    int cnt,
    ViPUInt32 retCnt,
  ) {
    return _viWriteFromFile(
      vi,
      filename,
      cnt,
      retCnt,
    );
  }

  late final _viWriteFromFilePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString, ViUInt32, ViPUInt32)>>('viWriteFromFile');
  late final _viWriteFromFile = _viWriteFromFilePtr.asFunction<int Function(int, ViConstString, int, ViPUInt32)>();

  int viAssertTrigger(
    int vi,
    int protocol,
  ) {
    return _viAssertTrigger(
      vi,
      protocol,
    );
  }

  late final _viAssertTriggerPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16)>>('viAssertTrigger');
  late final _viAssertTrigger = _viAssertTriggerPtr.asFunction<int Function(int, int)>();

  int viReadSTB(
    int vi,
    ViPUInt16 status,
  ) {
    return _viReadSTB(
      vi,
      status,
    );
  }

  late final _viReadSTBPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViPUInt16)>>('viReadSTB');
  late final _viReadSTB = _viReadSTBPtr.asFunction<int Function(int, ViPUInt16)>();

  int viClear(
    int vi,
  ) {
    return _viClear(
      vi,
    );
  }

  late final _viClearPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession)>>('viClear');
  late final _viClear = _viClearPtr.asFunction<int Function(int)>();

  int viSetBuf(
    int vi,
    int mask,
    int size,
  ) {
    return _viSetBuf(
      vi,
      mask,
      size,
    );
  }

  late final _viSetBufPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViUInt32)>>('viSetBuf');
  late final _viSetBuf = _viSetBufPtr.asFunction<int Function(int, int, int)>();

  int viFlush(
    int vi,
    int mask,
  ) {
    return _viFlush(
      vi,
      mask,
    );
  }

  late final _viFlushPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16)>>('viFlush');
  late final _viFlush = _viFlushPtr.asFunction<int Function(int, int)>();

  int viBufWrite(
    int vi,
    ViConstBuf buf,
    int cnt,
    ViPUInt32 retCnt,
  ) {
    return _viBufWrite(
      vi,
      buf,
      cnt,
      retCnt,
    );
  }

  late final _viBufWritePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstBuf, ViUInt32, ViPUInt32)>>('viBufWrite');
  late final _viBufWrite = _viBufWritePtr.asFunction<int Function(int, ViConstBuf, int, ViPUInt32)>();

  int viBufRead(
    int vi,
    ViPBuf buf,
    int cnt,
    ViPUInt32 retCnt,
  ) {
    return _viBufRead(
      vi,
      buf,
      cnt,
      retCnt,
    );
  }

  late final _viBufReadPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViPBuf, ViUInt32, ViPUInt32)>>('viBufRead');
  late final _viBufRead = _viBufReadPtr.asFunction<int Function(int, ViPBuf, int, ViPUInt32)>();

  int viPrintf(
    int vi,
    ViConstString writeFmt,
  ) {
    return _viPrintf(
      vi,
      writeFmt,
    );
  }

  late final _viPrintfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString)>>('viPrintf');
  late final _viPrintf = _viPrintfPtr.asFunction<int Function(int, ViConstString)>();

  int viVPrintf(
    int vi,
    ViConstString writeFmt,
    ViVAList params,
  ) {
    return _viVPrintf(
      vi,
      writeFmt,
      params,
    );
  }

  late final _viVPrintfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString, ViVAList)>>('viVPrintf');
  late final _viVPrintf = _viVPrintfPtr.asFunction<int Function(int, ViConstString, ViVAList)>();

  int viSPrintf(
    int vi,
    ViBuf buf,
    ViConstString writeFmt,
  ) {
    return _viSPrintf(
      vi,
      buf,
      writeFmt,
    );
  }

  late final _viSPrintfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViBuf, ViConstString)>>('viSPrintf');
  late final _viSPrintf = _viSPrintfPtr.asFunction<int Function(int, ViBuf, ViConstString)>();

  int viVSPrintf(
    int vi,
    ViBuf buf,
    ViConstString writeFmt,
    ViVAList parms,
  ) {
    return _viVSPrintf(
      vi,
      buf,
      writeFmt,
      parms,
    );
  }

  late final _viVSPrintfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViBuf, ViConstString, ViVAList)>>('viVSPrintf');
  late final _viVSPrintf = _viVSPrintfPtr.asFunction<int Function(int, ViBuf, ViConstString, ViVAList)>();

  int viScanf(
    int vi,
    ViConstString readFmt,
  ) {
    return _viScanf(
      vi,
      readFmt,
    );
  }

  late final _viScanfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString)>>('viScanf');
  late final _viScanf = _viScanfPtr.asFunction<int Function(int, ViConstString)>();

  int viVScanf(
    int vi,
    ViConstString readFmt,
    ViVAList params,
  ) {
    return _viVScanf(
      vi,
      readFmt,
      params,
    );
  }

  late final _viVScanfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString, ViVAList)>>('viVScanf');
  late final _viVScanf = _viVScanfPtr.asFunction<int Function(int, ViConstString, ViVAList)>();

  int viSScanf(
    int vi,
    ViConstBuf buf,
    ViConstString readFmt,
  ) {
    return _viSScanf(
      vi,
      buf,
      readFmt,
    );
  }

  late final _viSScanfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstBuf, ViConstString)>>('viSScanf');
  late final _viSScanf = _viSScanfPtr.asFunction<int Function(int, ViConstBuf, ViConstString)>();

  int viVSScanf(
    int vi,
    ViConstBuf buf,
    ViConstString readFmt,
    ViVAList parms,
  ) {
    return _viVSScanf(
      vi,
      buf,
      readFmt,
      parms,
    );
  }

  late final _viVSScanfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstBuf, ViConstString, ViVAList)>>('viVSScanf');
  late final _viVSScanf = _viVSScanfPtr.asFunction<int Function(int, ViConstBuf, ViConstString, ViVAList)>();

  int viQueryf(
    int vi,
    ViConstString writeFmt,
    ViConstString readFmt,
  ) {
    return _viQueryf(
      vi,
      writeFmt,
      readFmt,
    );
  }

  late final _viQueryfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString, ViConstString)>>('viQueryf');
  late final _viQueryf = _viQueryfPtr.asFunction<int Function(int, ViConstString, ViConstString)>();

  int viVQueryf(
    int vi,
    ViConstString writeFmt,
    ViConstString readFmt,
    ViVAList params,
  ) {
    return _viVQueryf(
      vi,
      writeFmt,
      readFmt,
      params,
    );
  }

  late final _viVQueryfPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstString, ViConstString, ViVAList)>>('viVQueryf');
  late final _viVQueryf = _viVQueryfPtr.asFunction<int Function(int, ViConstString, ViConstString, ViVAList)>();

  int viIn8(
    int vi,
    int space,
    int offset,
    ViPUInt8 val8,
  ) {
    return _viIn8(
      vi,
      space,
      offset,
      val8,
    );
  }

  late final _viIn8Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViPUInt8)>>('viIn8');
  late final _viIn8 = _viIn8Ptr.asFunction<int Function(int, int, int, ViPUInt8)>();

  int viOut8(
    int vi,
    int space,
    int offset,
    int val8,
  ) {
    return _viOut8(
      vi,
      space,
      offset,
      val8,
    );
  }

  late final _viOut8Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViUInt8)>>('viOut8');
  late final _viOut8 = _viOut8Ptr.asFunction<int Function(int, int, int, int)>();

  int viIn16(
    int vi,
    int space,
    int offset,
    ViPUInt16 val16,
  ) {
    return _viIn16(
      vi,
      space,
      offset,
      val16,
    );
  }

  late final _viIn16Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViPUInt16)>>('viIn16');
  late final _viIn16 = _viIn16Ptr.asFunction<int Function(int, int, int, ViPUInt16)>();

  int viOut16(
    int vi,
    int space,
    int offset,
    int val16,
  ) {
    return _viOut16(
      vi,
      space,
      offset,
      val16,
    );
  }

  late final _viOut16Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViUInt16)>>('viOut16');
  late final _viOut16 = _viOut16Ptr.asFunction<int Function(int, int, int, int)>();

  int viIn32(
    int vi,
    int space,
    int offset,
    ViPUInt32 val32,
  ) {
    return _viIn32(
      vi,
      space,
      offset,
      val32,
    );
  }

  late final _viIn32Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViPUInt32)>>('viIn32');
  late final _viIn32 = _viIn32Ptr.asFunction<int Function(int, int, int, ViPUInt32)>();

  int viOut32(
    int vi,
    int space,
    int offset,
    int val32,
  ) {
    return _viOut32(
      vi,
      space,
      offset,
      val32,
    );
  }

  late final _viOut32Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViUInt32)>>('viOut32');
  late final _viOut32 = _viOut32Ptr.asFunction<int Function(int, int, int, int)>();

  int viIn64(
    int vi,
    int space,
    int offset,
    ViPUInt64 val64,
  ) {
    return _viIn64(
      vi,
      space,
      offset,
      val64,
    );
  }

  late final _viIn64Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViPUInt64)>>('viIn64');
  late final _viIn64 = _viIn64Ptr.asFunction<int Function(int, int, int, ViPUInt64)>();

  int viOut64(
    int vi,
    int space,
    int offset,
    int val64,
  ) {
    return _viOut64(
      vi,
      space,
      offset,
      val64,
    );
  }

  late final _viOut64Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViUInt64)>>('viOut64');
  late final _viOut64 = _viOut64Ptr.asFunction<int Function(int, int, int, int)>();

  int viIn8Ex(
    int vi,
    int space,
    int offset,
    ViPUInt8 val8,
  ) {
    return _viIn8Ex(
      vi,
      space,
      offset,
      val8,
    );
  }

  late final _viIn8ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViPUInt8)>>('viIn8Ex');
  late final _viIn8Ex = _viIn8ExPtr.asFunction<int Function(int, int, int, ViPUInt8)>();

  int viOut8Ex(
    int vi,
    int space,
    int offset,
    int val8,
  ) {
    return _viOut8Ex(
      vi,
      space,
      offset,
      val8,
    );
  }

  late final _viOut8ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViUInt8)>>('viOut8Ex');
  late final _viOut8Ex = _viOut8ExPtr.asFunction<int Function(int, int, int, int)>();

  int viIn16Ex(
    int vi,
    int space,
    int offset,
    ViPUInt16 val16,
  ) {
    return _viIn16Ex(
      vi,
      space,
      offset,
      val16,
    );
  }

  late final _viIn16ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViPUInt16)>>('viIn16Ex');
  late final _viIn16Ex = _viIn16ExPtr.asFunction<int Function(int, int, int, ViPUInt16)>();

  int viOut16Ex(
    int vi,
    int space,
    int offset,
    int val16,
  ) {
    return _viOut16Ex(
      vi,
      space,
      offset,
      val16,
    );
  }

  late final _viOut16ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViUInt16)>>('viOut16Ex');
  late final _viOut16Ex = _viOut16ExPtr.asFunction<int Function(int, int, int, int)>();

  int viIn32Ex(
    int vi,
    int space,
    int offset,
    ViPUInt32 val32,
  ) {
    return _viIn32Ex(
      vi,
      space,
      offset,
      val32,
    );
  }

  late final _viIn32ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViPUInt32)>>('viIn32Ex');
  late final _viIn32Ex = _viIn32ExPtr.asFunction<int Function(int, int, int, ViPUInt32)>();

  int viOut32Ex(
    int vi,
    int space,
    int offset,
    int val32,
  ) {
    return _viOut32Ex(
      vi,
      space,
      offset,
      val32,
    );
  }

  late final _viOut32ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViUInt32)>>('viOut32Ex');
  late final _viOut32Ex = _viOut32ExPtr.asFunction<int Function(int, int, int, int)>();

  int viIn64Ex(
    int vi,
    int space,
    int offset,
    ViPUInt64 val64,
  ) {
    return _viIn64Ex(
      vi,
      space,
      offset,
      val64,
    );
  }

  late final _viIn64ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViPUInt64)>>('viIn64Ex');
  late final _viIn64Ex = _viIn64ExPtr.asFunction<int Function(int, int, int, ViPUInt64)>();

  int viOut64Ex(
    int vi,
    int space,
    int offset,
    int val64,
  ) {
    return _viOut64Ex(
      vi,
      space,
      offset,
      val64,
    );
  }

  late final _viOut64ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViUInt64)>>('viOut64Ex');
  late final _viOut64Ex = _viOut64ExPtr.asFunction<int Function(int, int, int, int)>();

  int viMoveIn8(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt8 buf8,
  ) {
    return _viMoveIn8(
      vi,
      space,
      offset,
      length,
      buf8,
    );
  }

  late final _viMoveIn8Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViAUInt8)>>('viMoveIn8');
  late final _viMoveIn8 = _viMoveIn8Ptr.asFunction<int Function(int, int, int, int, ViAUInt8)>();

  int viMoveOut8(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt8 buf8,
  ) {
    return _viMoveOut8(
      vi,
      space,
      offset,
      length,
      buf8,
    );
  }

  late final _viMoveOut8Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViAUInt8)>>('viMoveOut8');
  late final _viMoveOut8 = _viMoveOut8Ptr.asFunction<int Function(int, int, int, int, ViAUInt8)>();

  int viMoveIn16(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt16 buf16,
  ) {
    return _viMoveIn16(
      vi,
      space,
      offset,
      length,
      buf16,
    );
  }

  late final _viMoveIn16Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViAUInt16)>>('viMoveIn16');
  late final _viMoveIn16 = _viMoveIn16Ptr.asFunction<int Function(int, int, int, int, ViAUInt16)>();

  int viMoveOut16(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt16 buf16,
  ) {
    return _viMoveOut16(
      vi,
      space,
      offset,
      length,
      buf16,
    );
  }

  late final _viMoveOut16Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViAUInt16)>>('viMoveOut16');
  late final _viMoveOut16 = _viMoveOut16Ptr.asFunction<int Function(int, int, int, int, ViAUInt16)>();

  int viMoveIn32(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt32 buf32,
  ) {
    return _viMoveIn32(
      vi,
      space,
      offset,
      length,
      buf32,
    );
  }

  late final _viMoveIn32Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViAUInt32)>>('viMoveIn32');
  late final _viMoveIn32 = _viMoveIn32Ptr.asFunction<int Function(int, int, int, int, ViAUInt32)>();

  int viMoveOut32(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt32 buf32,
  ) {
    return _viMoveOut32(
      vi,
      space,
      offset,
      length,
      buf32,
    );
  }

  late final _viMoveOut32Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViAUInt32)>>('viMoveOut32');
  late final _viMoveOut32 = _viMoveOut32Ptr.asFunction<int Function(int, int, int, int, ViAUInt32)>();

  int viMoveIn64(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt64 buf64,
  ) {
    return _viMoveIn64(
      vi,
      space,
      offset,
      length,
      buf64,
    );
  }

  late final _viMoveIn64Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViAUInt64)>>('viMoveIn64');
  late final _viMoveIn64 = _viMoveIn64Ptr.asFunction<int Function(int, int, int, int, ViAUInt64)>();

  int viMoveOut64(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt64 buf64,
  ) {
    return _viMoveOut64(
      vi,
      space,
      offset,
      length,
      buf64,
    );
  }

  late final _viMoveOut64Ptr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViAUInt64)>>('viMoveOut64');
  late final _viMoveOut64 = _viMoveOut64Ptr.asFunction<int Function(int, int, int, int, ViAUInt64)>();

  int viMoveIn8Ex(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt8 buf8,
  ) {
    return _viMoveIn8Ex(
      vi,
      space,
      offset,
      length,
      buf8,
    );
  }

  late final _viMoveIn8ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViAUInt8)>>('viMoveIn8Ex');
  late final _viMoveIn8Ex = _viMoveIn8ExPtr.asFunction<int Function(int, int, int, int, ViAUInt8)>();

  int viMoveOut8Ex(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt8 buf8,
  ) {
    return _viMoveOut8Ex(
      vi,
      space,
      offset,
      length,
      buf8,
    );
  }

  late final _viMoveOut8ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViAUInt8)>>('viMoveOut8Ex');
  late final _viMoveOut8Ex = _viMoveOut8ExPtr.asFunction<int Function(int, int, int, int, ViAUInt8)>();

  int viMoveIn16Ex(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt16 buf16,
  ) {
    return _viMoveIn16Ex(
      vi,
      space,
      offset,
      length,
      buf16,
    );
  }

  late final _viMoveIn16ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViAUInt16)>>('viMoveIn16Ex');
  late final _viMoveIn16Ex = _viMoveIn16ExPtr.asFunction<int Function(int, int, int, int, ViAUInt16)>();

  int viMoveOut16Ex(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt16 buf16,
  ) {
    return _viMoveOut16Ex(
      vi,
      space,
      offset,
      length,
      buf16,
    );
  }

  late final _viMoveOut16ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViAUInt16)>>('viMoveOut16Ex');
  late final _viMoveOut16Ex = _viMoveOut16ExPtr.asFunction<int Function(int, int, int, int, ViAUInt16)>();

  int viMoveIn32Ex(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt32 buf32,
  ) {
    return _viMoveIn32Ex(
      vi,
      space,
      offset,
      length,
      buf32,
    );
  }

  late final _viMoveIn32ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViAUInt32)>>('viMoveIn32Ex');
  late final _viMoveIn32Ex = _viMoveIn32ExPtr.asFunction<int Function(int, int, int, int, ViAUInt32)>();

  int viMoveOut32Ex(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt32 buf32,
  ) {
    return _viMoveOut32Ex(
      vi,
      space,
      offset,
      length,
      buf32,
    );
  }

  late final _viMoveOut32ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViAUInt32)>>('viMoveOut32Ex');
  late final _viMoveOut32Ex = _viMoveOut32ExPtr.asFunction<int Function(int, int, int, int, ViAUInt32)>();

  int viMoveIn64Ex(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt64 buf64,
  ) {
    return _viMoveIn64Ex(
      vi,
      space,
      offset,
      length,
      buf64,
    );
  }

  late final _viMoveIn64ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViAUInt64)>>('viMoveIn64Ex');
  late final _viMoveIn64Ex = _viMoveIn64ExPtr.asFunction<int Function(int, int, int, int, ViAUInt64)>();

  int viMoveOut64Ex(
    int vi,
    int space,
    int offset,
    int length,
    ViAUInt64 buf64,
  ) {
    return _viMoveOut64Ex(
      vi,
      space,
      offset,
      length,
      buf64,
    );
  }

  late final _viMoveOut64ExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViAUInt64)>>('viMoveOut64Ex');
  late final _viMoveOut64Ex = _viMoveOut64ExPtr.asFunction<int Function(int, int, int, int, ViAUInt64)>();

  int viMove(
    int vi,
    int srcSpace,
    int srcOffset,
    int srcWidth,
    int destSpace,
    int destOffset,
    int destWidth,
    int srcLength,
  ) {
    return _viMove(
      vi,
      srcSpace,
      srcOffset,
      srcWidth,
      destSpace,
      destOffset,
      destWidth,
      srcLength,
    );
  }

  late final _viMovePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViUInt16, ViUInt16, ViBusAddress, ViUInt16, ViBusSize)>>('viMove');
  late final _viMove = _viMovePtr.asFunction<int Function(int, int, int, int, int, int, int, int)>();

  int viMoveAsync(
    int vi,
    int srcSpace,
    int srcOffset,
    int srcWidth,
    int destSpace,
    int destOffset,
    int destWidth,
    int srcLength,
    ViPJobId jobId,
  ) {
    return _viMoveAsync(
      vi,
      srcSpace,
      srcOffset,
      srcWidth,
      destSpace,
      destOffset,
      destWidth,
      srcLength,
      jobId,
    );
  }

  late final _viMoveAsyncPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViUInt16, ViUInt16, ViBusAddress, ViUInt16, ViBusSize, ViPJobId)>>('viMoveAsync');
  late final _viMoveAsync = _viMoveAsyncPtr.asFunction<int Function(int, int, int, int, int, int, int, int, ViPJobId)>();

  int viMoveEx(
    int vi,
    int srcSpace,
    int srcOffset,
    int srcWidth,
    int destSpace,
    int destOffset,
    int destWidth,
    int srcLength,
  ) {
    return _viMoveEx(
      vi,
      srcSpace,
      srcOffset,
      srcWidth,
      destSpace,
      destOffset,
      destWidth,
      srcLength,
    );
  }

  late final _viMoveExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViUInt16, ViUInt16, ViBusAddress64, ViUInt16, ViBusSize)>>('viMoveEx');
  late final _viMoveEx = _viMoveExPtr.asFunction<int Function(int, int, int, int, int, int, int, int)>();

  int viMoveAsyncEx(
    int vi,
    int srcSpace,
    int srcOffset,
    int srcWidth,
    int destSpace,
    int destOffset,
    int destWidth,
    int srcLength,
    ViPJobId jobId,
  ) {
    return _viMoveAsyncEx(
      vi,
      srcSpace,
      srcOffset,
      srcWidth,
      destSpace,
      destOffset,
      destWidth,
      srcLength,
      jobId,
    );
  }

  late final _viMoveAsyncExPtr =
      _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViUInt16, ViUInt16, ViBusAddress64, ViUInt16, ViBusSize, ViPJobId)>>('viMoveAsyncEx');
  late final _viMoveAsyncEx = _viMoveAsyncExPtr.asFunction<int Function(int, int, int, int, int, int, int, int, ViPJobId)>();

  int viMapAddress(
    int vi,
    int mapSpace,
    int mapOffset,
    int mapSize,
    int access,
    ViAddr suggested,
    ViPAddr address,
  ) {
    return _viMapAddress(
      vi,
      mapSpace,
      mapOffset,
      mapSize,
      access,
      suggested,
      address,
    );
  }

  late final _viMapAddressPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress, ViBusSize, ViBoolean, ViAddr, ViPAddr)>>('viMapAddress');
  late final _viMapAddress = _viMapAddressPtr.asFunction<int Function(int, int, int, int, int, ViAddr, ViPAddr)>();

  int viUnmapAddress(
    int vi,
  ) {
    return _viUnmapAddress(
      vi,
    );
  }

  late final _viUnmapAddressPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession)>>('viUnmapAddress');
  late final _viUnmapAddress = _viUnmapAddressPtr.asFunction<int Function(int)>();

  int viMapAddressEx(
    int vi,
    int mapSpace,
    int mapOffset,
    int mapSize,
    int access,
    ViAddr suggested,
    ViPAddr address,
  ) {
    return _viMapAddressEx(
      vi,
      mapSpace,
      mapOffset,
      mapSize,
      access,
      suggested,
      address,
    );
  }

  late final _viMapAddressExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViBusAddress64, ViBusSize, ViBoolean, ViAddr, ViPAddr)>>('viMapAddressEx');
  late final _viMapAddressEx = _viMapAddressExPtr.asFunction<int Function(int, int, int, int, int, ViAddr, ViPAddr)>();

  void viPeek8(
    int vi,
    ViAddr address,
    ViPUInt8 val8,
  ) {
    return _viPeek8(
      vi,
      address,
      val8,
    );
  }

  late final _viPeek8Ptr = _lookup<ffi.NativeFunction<ffi.Void Function(ViSession, ViAddr, ViPUInt8)>>('viPeek8');
  late final _viPeek8 = _viPeek8Ptr.asFunction<void Function(int, ViAddr, ViPUInt8)>();

  void viPoke8(
    int vi,
    ViAddr address,
    int val8,
  ) {
    return _viPoke8(
      vi,
      address,
      val8,
    );
  }

  late final _viPoke8Ptr = _lookup<ffi.NativeFunction<ffi.Void Function(ViSession, ViAddr, ViUInt8)>>('viPoke8');
  late final _viPoke8 = _viPoke8Ptr.asFunction<void Function(int, ViAddr, int)>();

  void viPeek16(
    int vi,
    ViAddr address,
    ViPUInt16 val16,
  ) {
    return _viPeek16(
      vi,
      address,
      val16,
    );
  }

  late final _viPeek16Ptr = _lookup<ffi.NativeFunction<ffi.Void Function(ViSession, ViAddr, ViPUInt16)>>('viPeek16');
  late final _viPeek16 = _viPeek16Ptr.asFunction<void Function(int, ViAddr, ViPUInt16)>();

  void viPoke16(
    int vi,
    ViAddr address,
    int val16,
  ) {
    return _viPoke16(
      vi,
      address,
      val16,
    );
  }

  late final _viPoke16Ptr = _lookup<ffi.NativeFunction<ffi.Void Function(ViSession, ViAddr, ViUInt16)>>('viPoke16');
  late final _viPoke16 = _viPoke16Ptr.asFunction<void Function(int, ViAddr, int)>();

  void viPeek32(
    int vi,
    ViAddr address,
    ViPUInt32 val32,
  ) {
    return _viPeek32(
      vi,
      address,
      val32,
    );
  }

  late final _viPeek32Ptr = _lookup<ffi.NativeFunction<ffi.Void Function(ViSession, ViAddr, ViPUInt32)>>('viPeek32');
  late final _viPeek32 = _viPeek32Ptr.asFunction<void Function(int, ViAddr, ViPUInt32)>();

  void viPoke32(
    int vi,
    ViAddr address,
    int val32,
  ) {
    return _viPoke32(
      vi,
      address,
      val32,
    );
  }

  late final _viPoke32Ptr = _lookup<ffi.NativeFunction<ffi.Void Function(ViSession, ViAddr, ViUInt32)>>('viPoke32');
  late final _viPoke32 = _viPoke32Ptr.asFunction<void Function(int, ViAddr, int)>();

  void viPeek64(
    int vi,
    ViAddr address,
    ViPUInt64 val64,
  ) {
    return _viPeek64(
      vi,
      address,
      val64,
    );
  }

  late final _viPeek64Ptr = _lookup<ffi.NativeFunction<ffi.Void Function(ViSession, ViAddr, ViPUInt64)>>('viPeek64');
  late final _viPeek64 = _viPeek64Ptr.asFunction<void Function(int, ViAddr, ViPUInt64)>();

  void viPoke64(
    int vi,
    ViAddr address,
    int val64,
  ) {
    return _viPoke64(
      vi,
      address,
      val64,
    );
  }

  late final _viPoke64Ptr = _lookup<ffi.NativeFunction<ffi.Void Function(ViSession, ViAddr, ViUInt64)>>('viPoke64');
  late final _viPoke64 = _viPoke64Ptr.asFunction<void Function(int, ViAddr, int)>();

  int viMemAlloc(
    int vi,
    int size,
    ViPBusAddress offset,
  ) {
    return _viMemAlloc(
      vi,
      size,
      offset,
    );
  }

  late final _viMemAllocPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViBusSize, ViPBusAddress)>>('viMemAlloc');
  late final _viMemAlloc = _viMemAllocPtr.asFunction<int Function(int, int, ViPBusAddress)>();

  int viMemFree(
    int vi,
    int offset,
  ) {
    return _viMemFree(
      vi,
      offset,
    );
  }

  late final _viMemFreePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViBusAddress)>>('viMemFree');
  late final _viMemFree = _viMemFreePtr.asFunction<int Function(int, int)>();

  int viMemAllocEx(
    int vi,
    int size,
    ViPBusAddress64 offset,
  ) {
    return _viMemAllocEx(
      vi,
      size,
      offset,
    );
  }

  late final _viMemAllocExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViBusSize, ViPBusAddress64)>>('viMemAllocEx');
  late final _viMemAllocEx = _viMemAllocExPtr.asFunction<int Function(int, int, ViPBusAddress64)>();

  int viMemFreeEx(
    int vi,
    int offset,
  ) {
    return _viMemFreeEx(
      vi,
      offset,
    );
  }

  late final _viMemFreeExPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViBusAddress64)>>('viMemFreeEx');
  late final _viMemFreeEx = _viMemFreeExPtr.asFunction<int Function(int, int)>();

  int viGpibControlREN(
    int vi,
    int mode,
  ) {
    return _viGpibControlREN(
      vi,
      mode,
    );
  }

  late final _viGpibControlRENPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16)>>('viGpibControlREN');
  late final _viGpibControlREN = _viGpibControlRENPtr.asFunction<int Function(int, int)>();

  int viGpibControlATN(
    int vi,
    int mode,
  ) {
    return _viGpibControlATN(
      vi,
      mode,
    );
  }

  late final _viGpibControlATNPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16)>>('viGpibControlATN');
  late final _viGpibControlATN = _viGpibControlATNPtr.asFunction<int Function(int, int)>();

  int viGpibSendIFC(
    int vi,
  ) {
    return _viGpibSendIFC(
      vi,
    );
  }

  late final _viGpibSendIFCPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession)>>('viGpibSendIFC');
  late final _viGpibSendIFC = _viGpibSendIFCPtr.asFunction<int Function(int)>();

  int viGpibCommand(
    int vi,
    ViConstBuf cmd,
    int cnt,
    ViPUInt32 retCnt,
  ) {
    return _viGpibCommand(
      vi,
      cmd,
      cnt,
      retCnt,
    );
  }

  late final _viGpibCommandPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViConstBuf, ViUInt32, ViPUInt32)>>('viGpibCommand');
  late final _viGpibCommand = _viGpibCommandPtr.asFunction<int Function(int, ViConstBuf, int, ViPUInt32)>();

  int viGpibPassControl(
    int vi,
    int primAddr,
    int secAddr,
  ) {
    return _viGpibPassControl(
      vi,
      primAddr,
      secAddr,
    );
  }

  late final _viGpibPassControlPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViUInt16)>>('viGpibPassControl');
  late final _viGpibPassControl = _viGpibPassControlPtr.asFunction<int Function(int, int, int)>();

  int viVxiCommandQuery(
    int vi,
    int mode,
    int cmd,
    ViPUInt32 response,
  ) {
    return _viVxiCommandQuery(
      vi,
      mode,
      cmd,
      response,
    );
  }

  late final _viVxiCommandQueryPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16, ViUInt32, ViPUInt32)>>('viVxiCommandQuery');
  late final _viVxiCommandQuery = _viVxiCommandQueryPtr.asFunction<int Function(int, int, int, ViPUInt32)>();

  int viAssertUtilSignal(
    int vi,
    int line,
  ) {
    return _viAssertUtilSignal(
      vi,
      line,
    );
  }

  late final _viAssertUtilSignalPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViUInt16)>>('viAssertUtilSignal');
  late final _viAssertUtilSignal = _viAssertUtilSignalPtr.asFunction<int Function(int, int)>();

  int viAssertIntrSignal(
    int vi,
    int mode,
    int statusID,
  ) {
    return _viAssertIntrSignal(
      vi,
      mode,
      statusID,
    );
  }

  late final _viAssertIntrSignalPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViInt16, ViUInt32)>>('viAssertIntrSignal');
  late final _viAssertIntrSignal = _viAssertIntrSignalPtr.asFunction<int Function(int, int, int)>();

  int viMapTrigger(
    int vi,
    int trigSrc,
    int trigDest,
    int mode,
  ) {
    return _viMapTrigger(
      vi,
      trigSrc,
      trigDest,
      mode,
    );
  }

  late final _viMapTriggerPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViInt16, ViInt16, ViUInt16)>>('viMapTrigger');
  late final _viMapTrigger = _viMapTriggerPtr.asFunction<int Function(int, int, int, int)>();

  int viUnmapTrigger(
    int vi,
    int trigSrc,
    int trigDest,
  ) {
    return _viUnmapTrigger(
      vi,
      trigSrc,
      trigDest,
    );
  }

  late final _viUnmapTriggerPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViInt16, ViInt16)>>('viUnmapTrigger');
  late final _viUnmapTrigger = _viUnmapTriggerPtr.asFunction<int Function(int, int, int)>();

  int viUsbControlOut(
    int vi,
    int bmRequestType,
    int bRequest,
    int wValue,
    int wIndex,
    int wLength,
    ViConstBuf buf,
  ) {
    return _viUsbControlOut(
      vi,
      bmRequestType,
      bRequest,
      wValue,
      wIndex,
      wLength,
      buf,
    );
  }

  late final _viUsbControlOutPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViInt16, ViInt16, ViUInt16, ViUInt16, ViUInt16, ViConstBuf)>>('viUsbControlOut');
  late final _viUsbControlOut = _viUsbControlOutPtr.asFunction<int Function(int, int, int, int, int, int, ViConstBuf)>();

  int viUsbControlIn(
    int vi,
    int bmRequestType,
    int bRequest,
    int wValue,
    int wIndex,
    int wLength,
    ViPBuf buf,
    ViPUInt16 retCnt,
  ) {
    return _viUsbControlIn(
      vi,
      bmRequestType,
      bRequest,
      wValue,
      wIndex,
      wLength,
      buf,
      retCnt,
    );
  }

  late final _viUsbControlInPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViInt16, ViInt16, ViUInt16, ViUInt16, ViUInt16, ViPBuf, ViPUInt16)>>('viUsbControlIn');
  late final _viUsbControlIn = _viUsbControlInPtr.asFunction<int Function(int, int, int, int, int, int, ViPBuf, ViPUInt16)>();

  int viPxiReserveTriggers(
    int vi,
    int cnt,
    ViAInt16 trigBuses,
    ViAInt16 trigLines,
    ViPInt16 failureIndex,
  ) {
    return _viPxiReserveTriggers(
      vi,
      cnt,
      trigBuses,
      trigLines,
      failureIndex,
    );
  }

  late final _viPxiReserveTriggersPtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViInt16, ViAInt16, ViAInt16, ViPInt16)>>('viPxiReserveTriggers');
  late final _viPxiReserveTriggers = _viPxiReserveTriggersPtr.asFunction<int Function(int, int, ViAInt16, ViAInt16, ViPInt16)>();

  int viVxiServantResponse(
    int vi,
    int mode,
    int resp,
  ) {
    return _viVxiServantResponse(
      vi,
      mode,
      resp,
    );
  }

  late final _viVxiServantResponsePtr = _lookup<ffi.NativeFunction<ViStatus Function(ViSession, ViInt16, ViUInt32)>>('viVxiServantResponse');
  late final _viVxiServantResponse = _viVxiServantResponsePtr.asFunction<int Function(int, int, int)>();
}

typedef ViStatus = ViInt32;
typedef ViInt32 = ffi.Int;
typedef DartViInt32 = int;
typedef ViPSession = ffi.Pointer<ViSession>;
typedef ViSession = ViObject;
typedef ViObject = ViUInt32;
typedef ViUInt32 = ffi.UnsignedInt;
typedef DartViUInt32 = int;
typedef ViConstString = ffi.Pointer<ViChar>;
typedef ViChar = ffi.Char;
typedef DartViChar = int;
typedef ViPFindList = ffi.Pointer<ViFindList>;
typedef ViFindList = ViObject;
typedef ViPUInt32 = ffi.Pointer<ViUInt32>;
typedef ViConstRsrc = ViConstString;
typedef ViPUInt16 = ffi.Pointer<ViUInt16>;
typedef ViUInt16 = ffi.UnsignedShort;
typedef DartViUInt16 = int;
typedef ViAccessMode = ViUInt32;
typedef ViAttr = ViUInt32;
typedef ViAttrState = ViUInt64;
typedef ViUInt64 = u_int64_t;
typedef u_int64_t = ffi.UnsignedLongLong;
typedef Dartu_int64_t = int;
typedef ViJobId = ViUInt32;
typedef ViConstKeyId = ViConstString;
typedef ViEventType = ViUInt32;
typedef ViEventFilter = ViUInt32;
typedef ViPEventType = ffi.Pointer<ViEventType>;
typedef ViPEvent = ffi.Pointer<ViEvent>;
typedef ViEvent = ViObject;
typedef ViHndlr = ffi.Pointer<ffi.NativeFunction<ViHndlrFunction>>;
typedef ViHndlrFunction = ViStatus Function(ViSession vi, ViEventType eventType, ViEvent event, ViAddr userHandle);
typedef DartViHndlrFunction = DartViInt32 Function(DartViUInt32 vi, DartViUInt32 eventType, DartViUInt32 event, ViAddr userHandle);
typedef ViAddr = ffi.Pointer<ffi.Void>;
typedef ViPBuf = ViPByte;
typedef ViPByte = ffi.Pointer<ViByte>;
typedef ViByte = ffi.UnsignedChar;
typedef DartViByte = int;
typedef ViPJobId = ffi.Pointer<ViJobId>;
typedef ViConstBuf = ffi.Pointer<ViByte>;
typedef ViVAList = va_list;
typedef va_list = __builtin_va_list;
typedef __builtin_va_list = ffi.Pointer<ffi.Char>;
typedef ViBuf = ViPByte;
typedef ViBusAddress = ViUInt64;
typedef ViPUInt8 = ffi.Pointer<ViUInt8>;
typedef ViUInt8 = ffi.UnsignedChar;
typedef DartViUInt8 = int;
typedef ViPUInt64 = ffi.Pointer<ViUInt64>;
typedef ViBusAddress64 = ViUInt64;
typedef ViBusSize = ViUInt64;
typedef ViAUInt8 = ffi.Pointer<ViUInt8>;
typedef ViAUInt16 = ffi.Pointer<ViUInt16>;
typedef ViAUInt32 = ffi.Pointer<ViUInt32>;
typedef ViAUInt64 = ffi.Pointer<ViUInt64>;
typedef ViBoolean = ViUInt16;
typedef ViPAddr = ffi.Pointer<ViAddr>;
typedef ViPBusAddress = ffi.Pointer<ViBusAddress>;
typedef ViPBusAddress64 = ffi.Pointer<ViBusAddress64>;
typedef ViInt16 = ffi.Short;
typedef DartViInt16 = int;
typedef ViAInt16 = ffi.Pointer<ViInt16>;
typedef ViPInt16 = ffi.Pointer<ViInt16>;

const int _VI_ERROR = -2147483648;

const int VI_SUCCESS = 0;

const int VI_NULL = 0;

const int VI_TRUE = 1;

const int VI_FALSE = 0;

const int VI_SPEC_VERSION = 7340032;

const int VI_ATTR_RSRC_CLASS = 3221159937;

const int VI_ATTR_RSRC_NAME = 3221159938;

const int VI_ATTR_RSRC_IMPL_VERSION = 1073676291;

const int VI_ATTR_RSRC_LOCK_STATE = 1073676292;

const int VI_ATTR_MAX_QUEUE_LENGTH = 1073676293;

const int VI_ATTR_USER_DATA_32 = 1073676295;

const int VI_ATTR_FDC_CHNL = 1073676301;

const int VI_ATTR_FDC_MODE = 1073676303;

const int VI_ATTR_FDC_GEN_SIGNAL_EN = 1073676305;

const int VI_ATTR_FDC_USE_PAIR = 1073676307;

const int VI_ATTR_SEND_END_EN = 1073676310;

const int VI_ATTR_TERMCHAR = 1073676312;

const int VI_ATTR_TMO_VALUE = 1073676314;

const int VI_ATTR_GPIB_READDR_EN = 1073676315;

const int VI_ATTR_IO_PROT = 1073676316;

const int VI_ATTR_DMA_ALLOW_EN = 1073676318;

const int VI_ATTR_ASRL_BAUD = 1073676321;

const int VI_ATTR_ASRL_DATA_BITS = 1073676322;

const int VI_ATTR_ASRL_PARITY = 1073676323;

const int VI_ATTR_ASRL_STOP_BITS = 1073676324;

const int VI_ATTR_ASRL_FLOW_CNTRL = 1073676325;

const int VI_ATTR_RD_BUF_OPER_MODE = 1073676330;

const int VI_ATTR_RD_BUF_SIZE = 1073676331;

const int VI_ATTR_WR_BUF_OPER_MODE = 1073676333;

const int VI_ATTR_WR_BUF_SIZE = 1073676334;

const int VI_ATTR_SUPPRESS_END_EN = 1073676342;

const int VI_ATTR_TERMCHAR_EN = 1073676344;

const int VI_ATTR_DEST_ACCESS_PRIV = 1073676345;

const int VI_ATTR_DEST_BYTE_ORDER = 1073676346;

const int VI_ATTR_SRC_ACCESS_PRIV = 1073676348;

const int VI_ATTR_SRC_BYTE_ORDER = 1073676349;

const int VI_ATTR_SRC_INCREMENT = 1073676352;

const int VI_ATTR_DEST_INCREMENT = 1073676353;

const int VI_ATTR_WIN_ACCESS_PRIV = 1073676357;

const int VI_ATTR_WIN_BYTE_ORDER = 1073676359;

const int VI_ATTR_GPIB_ATN_STATE = 1073676375;

const int VI_ATTR_GPIB_ADDR_STATE = 1073676380;

const int VI_ATTR_GPIB_CIC_STATE = 1073676382;

const int VI_ATTR_GPIB_NDAC_STATE = 1073676386;

const int VI_ATTR_GPIB_SRQ_STATE = 1073676391;

const int VI_ATTR_GPIB_SYS_CNTRL_STATE = 1073676392;

const int VI_ATTR_GPIB_HS488_CBL_LEN = 1073676393;

const int VI_ATTR_CMDR_LA = 1073676395;

const int VI_ATTR_VXI_DEV_CLASS = 1073676396;

const int VI_ATTR_MAINFRAME_LA = 1073676400;

const int VI_ATTR_MANF_NAME = 3221160050;

const int VI_ATTR_MODEL_NAME = 3221160055;

const int VI_ATTR_VXI_VME_INTR_STATUS = 1073676427;

const int VI_ATTR_VXI_TRIG_STATUS = 1073676429;

const int VI_ATTR_VXI_VME_SYSFAIL_STATE = 1073676436;

const int VI_ATTR_WIN_BASE_ADDR_32 = 1073676440;

const int VI_ATTR_WIN_SIZE_32 = 1073676442;

const int VI_ATTR_ASRL_AVAIL_NUM = 1073676460;

const int VI_ATTR_MEM_BASE_32 = 1073676461;

const int VI_ATTR_ASRL_CTS_STATE = 1073676462;

const int VI_ATTR_ASRL_DCD_STATE = 1073676463;

const int VI_ATTR_ASRL_DSR_STATE = 1073676465;

const int VI_ATTR_ASRL_DTR_STATE = 1073676466;

const int VI_ATTR_ASRL_END_IN = 1073676467;

const int VI_ATTR_ASRL_END_OUT = 1073676468;

const int VI_ATTR_ASRL_REPLACE_CHAR = 1073676478;

const int VI_ATTR_ASRL_RI_STATE = 1073676479;

const int VI_ATTR_ASRL_RTS_STATE = 1073676480;

const int VI_ATTR_ASRL_XON_CHAR = 1073676481;

const int VI_ATTR_ASRL_XOFF_CHAR = 1073676482;

const int VI_ATTR_WIN_ACCESS = 1073676483;

const int VI_ATTR_RM_SESSION = 1073676484;

const int VI_ATTR_VXI_LA = 1073676501;

const int VI_ATTR_MANF_ID = 1073676505;

const int VI_ATTR_MEM_SIZE_32 = 1073676509;

const int VI_ATTR_MEM_SPACE = 1073676510;

const int VI_ATTR_MODEL_CODE = 1073676511;

const int VI_ATTR_SLOT = 1073676520;

const int VI_ATTR_INTF_INST_NAME = 3221160169;

const int VI_ATTR_IMMEDIATE_SERV = 1073676544;

const int VI_ATTR_INTF_PARENT_NUM = 1073676545;

const int VI_ATTR_RSRC_SPEC_VERSION = 1073676656;

const int VI_ATTR_INTF_TYPE = 1073676657;

const int VI_ATTR_GPIB_PRIMARY_ADDR = 1073676658;

const int VI_ATTR_GPIB_SECONDARY_ADDR = 1073676659;

const int VI_ATTR_RSRC_MANF_NAME = 3221160308;

const int VI_ATTR_RSRC_MANF_ID = 1073676661;

const int VI_ATTR_INTF_NUM = 1073676662;

const int VI_ATTR_TRIG_ID = 1073676663;

const int VI_ATTR_GPIB_REN_STATE = 1073676673;

const int VI_ATTR_GPIB_UNADDR_EN = 1073676676;

const int VI_ATTR_DEV_STATUS_BYTE = 1073676681;

const int VI_ATTR_FILE_APPEND_EN = 1073676690;

const int VI_ATTR_VXI_TRIG_SUPPORT = 1073676692;

const int VI_ATTR_TCPIP_ADDR = 3221160341;

const int VI_ATTR_TCPIP_HOSTNAME = 3221160342;

const int VI_ATTR_TCPIP_PORT = 1073676695;

const int VI_ATTR_TCPIP_DEVICE_NAME = 3221160345;

const int VI_ATTR_TCPIP_NODELAY = 1073676698;

const int VI_ATTR_TCPIP_KEEPALIVE = 1073676699;

const int VI_ATTR_4882_COMPLIANT = 1073676703;

const int VI_ATTR_USB_SERIAL_NUM = 3221160352;

const int VI_ATTR_USB_INTFC_NUM = 1073676705;

const int VI_ATTR_USB_PROTOCOL = 1073676711;

const int VI_ATTR_USB_MAX_INTR_SIZE = 1073676719;

const int VI_ATTR_PXI_DEV_NUM = 1073676801;

const int VI_ATTR_PXI_FUNC_NUM = 1073676802;

const int VI_ATTR_PXI_BUS_NUM = 1073676805;

const int VI_ATTR_PXI_CHASSIS = 1073676806;

const int VI_ATTR_PXI_SLOTPATH = 3221160455;

const int VI_ATTR_PXI_SLOT_LBUS_LEFT = 1073676808;

const int VI_ATTR_PXI_SLOT_LBUS_RIGHT = 1073676809;

const int VI_ATTR_PXI_TRIG_BUS = 1073676810;

const int VI_ATTR_PXI_STAR_TRIG_BUS = 1073676811;

const int VI_ATTR_PXI_STAR_TRIG_LINE = 1073676812;

const int VI_ATTR_PXI_SRC_TRIG_BUS = 1073676813;

const int VI_ATTR_PXI_DEST_TRIG_BUS = 1073676814;

const int VI_ATTR_PXI_MEM_TYPE_BAR0 = 1073676817;

const int VI_ATTR_PXI_MEM_TYPE_BAR1 = 1073676818;

const int VI_ATTR_PXI_MEM_TYPE_BAR2 = 1073676819;

const int VI_ATTR_PXI_MEM_TYPE_BAR3 = 1073676820;

const int VI_ATTR_PXI_MEM_TYPE_BAR4 = 1073676821;

const int VI_ATTR_PXI_MEM_TYPE_BAR5 = 1073676822;

const int VI_ATTR_PXI_MEM_BASE_BAR0_32 = 1073676833;

const int VI_ATTR_PXI_MEM_BASE_BAR1_32 = 1073676834;

const int VI_ATTR_PXI_MEM_BASE_BAR2_32 = 1073676835;

const int VI_ATTR_PXI_MEM_BASE_BAR3_32 = 1073676836;

const int VI_ATTR_PXI_MEM_BASE_BAR4_32 = 1073676837;

const int VI_ATTR_PXI_MEM_BASE_BAR5_32 = 1073676838;

const int VI_ATTR_PXI_MEM_BASE_BAR0_64 = 1073676840;

const int VI_ATTR_PXI_MEM_BASE_BAR1_64 = 1073676841;

const int VI_ATTR_PXI_MEM_BASE_BAR2_64 = 1073676842;

const int VI_ATTR_PXI_MEM_BASE_BAR3_64 = 1073676843;

const int VI_ATTR_PXI_MEM_BASE_BAR4_64 = 1073676844;

const int VI_ATTR_PXI_MEM_BASE_BAR5_64 = 1073676845;

const int VI_ATTR_PXI_MEM_SIZE_BAR0_32 = 1073676849;

const int VI_ATTR_PXI_MEM_SIZE_BAR1_32 = 1073676850;

const int VI_ATTR_PXI_MEM_SIZE_BAR2_32 = 1073676851;

const int VI_ATTR_PXI_MEM_SIZE_BAR3_32 = 1073676852;

const int VI_ATTR_PXI_MEM_SIZE_BAR4_32 = 1073676853;

const int VI_ATTR_PXI_MEM_SIZE_BAR5_32 = 1073676854;

const int VI_ATTR_PXI_MEM_SIZE_BAR0_64 = 1073676856;

const int VI_ATTR_PXI_MEM_SIZE_BAR1_64 = 1073676857;

const int VI_ATTR_PXI_MEM_SIZE_BAR2_64 = 1073676858;

const int VI_ATTR_PXI_MEM_SIZE_BAR3_64 = 1073676859;

const int VI_ATTR_PXI_MEM_SIZE_BAR4_64 = 1073676860;

const int VI_ATTR_PXI_MEM_SIZE_BAR5_64 = 1073676861;

const int VI_ATTR_PXI_IS_EXPRESS = 1073676864;

const int VI_ATTR_PXI_SLOT_LWIDTH = 1073676865;

const int VI_ATTR_PXI_MAX_LWIDTH = 1073676866;

const int VI_ATTR_PXI_ACTUAL_LWIDTH = 1073676867;

const int VI_ATTR_PXI_DSTAR_BUS = 1073676868;

const int VI_ATTR_PXI_DSTAR_SET = 1073676869;

const int VI_ATTR_PXI_ALLOW_WRITE_COMBINE = 1073676870;

const int VI_ATTR_TCPIP_HISLIP_OVERLAP_EN = 1073677056;

const int VI_ATTR_TCPIP_HISLIP_VERSION = 1073677057;

const int VI_ATTR_TCPIP_HISLIP_MAX_MESSAGE_KB = 1073677058;

const int VI_ATTR_TCPIP_IS_HISLIP = 1073677059;

const int VI_ATTR_JOB_ID = 1073692678;

const int VI_ATTR_EVENT_TYPE = 1073692688;

const int VI_ATTR_SIGP_STATUS_ID = 1073692689;

const int VI_ATTR_RECV_TRIG_ID = 1073692690;

const int VI_ATTR_INTR_STATUS_ID = 1073692707;

const int VI_ATTR_STATUS = 1073692709;

const int VI_ATTR_RET_COUNT_32 = 1073692710;

const int VI_ATTR_BUFFER = 1073692711;

const int VI_ATTR_RECV_INTR_LEVEL = 1073692737;

const int VI_ATTR_OPER_NAME = 3221176386;

const int VI_ATTR_GPIB_RECV_CIC_STATE = 1073693075;

const int VI_ATTR_RECV_TCPIP_ADDR = 3221176728;

const int VI_ATTR_USB_RECV_INTR_SIZE = 1073693104;

const int VI_ATTR_USB_RECV_INTR_DATA = 3221176753;

const int VI_ATTR_PXI_RECV_INTR_SEQ = 1073693248;

const int VI_ATTR_PXI_RECV_INTR_DATA = 1073693249;

const int VI_ATTR_USER_DATA_64 = 1073676298;

const int VI_ATTR_RET_COUNT_64 = 1073692712;

const int VI_ATTR_USER_DATA = 1073676298;

const int VI_ATTR_RET_COUNT = 1073692712;

const int VI_ATTR_WIN_BASE_ADDR_64 = 1073676443;

const int VI_ATTR_WIN_SIZE_64 = 1073676444;

const int VI_ATTR_MEM_BASE_64 = 1073676496;

const int VI_ATTR_MEM_SIZE_64 = 1073676497;

const int VI_ATTR_WIN_BASE_ADDR = 1073676443;

const int VI_ATTR_WIN_SIZE = 1073676444;

const int VI_ATTR_MEM_BASE = 1073676496;

const int VI_ATTR_MEM_SIZE = 1073676497;

const int VI_ATTR_PXI_MEM_BASE_BAR0 = 1073676840;

const int VI_ATTR_PXI_MEM_BASE_BAR1 = 1073676841;

const int VI_ATTR_PXI_MEM_BASE_BAR2 = 1073676842;

const int VI_ATTR_PXI_MEM_BASE_BAR3 = 1073676843;

const int VI_ATTR_PXI_MEM_BASE_BAR4 = 1073676844;

const int VI_ATTR_PXI_MEM_BASE_BAR5 = 1073676845;

const int VI_ATTR_PXI_MEM_SIZE_BAR0 = 1073676856;

const int VI_ATTR_PXI_MEM_SIZE_BAR1 = 1073676857;

const int VI_ATTR_PXI_MEM_SIZE_BAR2 = 1073676858;

const int VI_ATTR_PXI_MEM_SIZE_BAR3 = 1073676859;

const int VI_ATTR_PXI_MEM_SIZE_BAR4 = 1073676860;

const int VI_ATTR_PXI_MEM_SIZE_BAR5 = 1073676861;

const int VI_EVENT_IO_COMPLETION = 1073684489;

const int VI_EVENT_TRIG = 3221168138;

const int VI_EVENT_SERVICE_REQ = 1073684491;

const int VI_EVENT_CLEAR = 1073684493;

const int VI_EVENT_EXCEPTION = 3221168142;

const int VI_EVENT_GPIB_CIC = 1073684498;

const int VI_EVENT_GPIB_TALK = 1073684499;

const int VI_EVENT_GPIB_LISTEN = 1073684500;

const int VI_EVENT_VXI_VME_SYSFAIL = 1073684509;

const int VI_EVENT_VXI_VME_SYSRESET = 1073684510;

const int VI_EVENT_VXI_SIGP = 1073684512;

const int VI_EVENT_VXI_VME_INTR = 3221168161;

const int VI_EVENT_PXI_INTR = 1073684514;

const int VI_EVENT_TCPIP_CONNECT = 1073684534;

const int VI_EVENT_USB_INTR = 1073684535;

const int VI_ALL_ENABLED_EVENTS = 1073709055;

const int VI_SUCCESS_EVENT_EN = 1073676290;

const int VI_SUCCESS_EVENT_DIS = 1073676291;

const int VI_SUCCESS_QUEUE_EMPTY = 1073676292;

const int VI_SUCCESS_TERM_CHAR = 1073676293;

const int VI_SUCCESS_MAX_CNT = 1073676294;

const int VI_SUCCESS_DEV_NPRESENT = 1073676413;

const int VI_SUCCESS_TRIG_MAPPED = 1073676414;

const int VI_SUCCESS_QUEUE_NEMPTY = 1073676416;

const int VI_SUCCESS_NCHAIN = 1073676440;

const int VI_SUCCESS_NESTED_SHARED = 1073676441;

const int VI_SUCCESS_NESTED_EXCLUSIVE = 1073676442;

const int VI_SUCCESS_SYNC = 1073676443;

const int VI_WARN_QUEUE_OVERFLOW = 1073676300;

const int VI_WARN_CONFIG_NLOADED = 1073676407;

const int VI_WARN_NULL_OBJECT = 1073676418;

const int VI_WARN_NSUP_ATTR_STATE = 1073676420;

const int VI_WARN_UNKNOWN_STATUS = 1073676421;

const int VI_WARN_NSUP_BUF = 1073676424;

const int VI_WARN_EXT_FUNC_NIMPL = 1073676457;

const int VI_ERROR_SYSTEM_ERROR = -1073807360;

const int VI_ERROR_INV_OBJECT = -1073807346;

const int VI_ERROR_RSRC_LOCKED = -1073807345;

const int VI_ERROR_INV_EXPR = -1073807344;

const int VI_ERROR_RSRC_NFOUND = -1073807343;

const int VI_ERROR_INV_RSRC_NAME = -1073807342;

const int VI_ERROR_INV_ACC_MODE = -1073807341;

const int VI_ERROR_TMO = -1073807339;

const int VI_ERROR_CLOSING_FAILED = -1073807338;

const int VI_ERROR_INV_DEGREE = -1073807333;

const int VI_ERROR_INV_JOB_ID = -1073807332;

const int VI_ERROR_NSUP_ATTR = -1073807331;

const int VI_ERROR_NSUP_ATTR_STATE = -1073807330;

const int VI_ERROR_ATTR_READONLY = -1073807329;

const int VI_ERROR_INV_LOCK_TYPE = -1073807328;

const int VI_ERROR_INV_ACCESS_KEY = -1073807327;

const int VI_ERROR_INV_EVENT = -1073807322;

const int VI_ERROR_INV_MECH = -1073807321;

const int VI_ERROR_HNDLR_NINSTALLED = -1073807320;

const int VI_ERROR_INV_HNDLR_REF = -1073807319;

const int VI_ERROR_INV_CONTEXT = -1073807318;

const int VI_ERROR_QUEUE_OVERFLOW = -1073807315;

const int VI_ERROR_NENABLED = -1073807313;

const int VI_ERROR_ABORT = -1073807312;

const int VI_ERROR_RAW_WR_PROT_VIOL = -1073807308;

const int VI_ERROR_RAW_RD_PROT_VIOL = -1073807307;

const int VI_ERROR_OUTP_PROT_VIOL = -1073807306;

const int VI_ERROR_INP_PROT_VIOL = -1073807305;

const int VI_ERROR_BERR = -1073807304;

const int VI_ERROR_IN_PROGRESS = -1073807303;

const int VI_ERROR_INV_SETUP = -1073807302;

const int VI_ERROR_QUEUE_ERROR = -1073807301;

const int VI_ERROR_ALLOC = -1073807300;

const int VI_ERROR_INV_MASK = -1073807299;

const int VI_ERROR_IO = -1073807298;

const int VI_ERROR_INV_FMT = -1073807297;

const int VI_ERROR_NSUP_FMT = -1073807295;

const int VI_ERROR_LINE_IN_USE = -1073807294;

const int VI_ERROR_LINE_NRESERVED = -1073807293;

const int VI_ERROR_NSUP_MODE = -1073807290;

const int VI_ERROR_SRQ_NOCCURRED = -1073807286;

const int VI_ERROR_INV_SPACE = -1073807282;

const int VI_ERROR_INV_OFFSET = -1073807279;

const int VI_ERROR_INV_WIDTH = -1073807278;

const int VI_ERROR_NSUP_OFFSET = -1073807276;

const int VI_ERROR_NSUP_VAR_WIDTH = -1073807275;

const int VI_ERROR_WINDOW_NMAPPED = -1073807273;

const int VI_ERROR_RESP_PENDING = -1073807271;

const int VI_ERROR_NLISTENERS = -1073807265;

const int VI_ERROR_NCIC = -1073807264;

const int VI_ERROR_NSYS_CNTLR = -1073807263;

const int VI_ERROR_NSUP_OPER = -1073807257;

const int VI_ERROR_INTR_PENDING = -1073807256;

const int VI_ERROR_ASRL_PARITY = -1073807254;

const int VI_ERROR_ASRL_FRAMING = -1073807253;

const int VI_ERROR_ASRL_OVERRUN = -1073807252;

const int VI_ERROR_TRIG_NMAPPED = -1073807250;

const int VI_ERROR_NSUP_ALIGN_OFFSET = -1073807248;

const int VI_ERROR_USER_BUF = -1073807247;

const int VI_ERROR_RSRC_BUSY = -1073807246;

const int VI_ERROR_NSUP_WIDTH = -1073807242;

const int VI_ERROR_INV_PARAMETER = -1073807240;

const int VI_ERROR_INV_PROT = -1073807239;

const int VI_ERROR_INV_SIZE = -1073807237;

const int VI_ERROR_WINDOW_MAPPED = -1073807232;

const int VI_ERROR_NIMPL_OPER = -1073807231;

const int VI_ERROR_INV_LENGTH = -1073807229;

const int VI_ERROR_INV_MODE = -1073807215;

const int VI_ERROR_SESN_NLOCKED = -1073807204;

const int VI_ERROR_MEM_NSHARED = -1073807203;

const int VI_ERROR_LIBRARY_NFOUND = -1073807202;

const int VI_ERROR_NSUP_INTR = -1073807201;

const int VI_ERROR_INV_LINE = -1073807200;

const int VI_ERROR_FILE_ACCESS = -1073807199;

const int VI_ERROR_FILE_IO = -1073807198;

const int VI_ERROR_NSUP_LINE = -1073807197;

const int VI_ERROR_NSUP_MECH = -1073807196;

const int VI_ERROR_INTF_NUM_NCONFIG = -1073807195;

const int VI_ERROR_CONN_LOST = -1073807194;

const int VI_ERROR_MACHINE_NAVAIL = -1073807193;

const int VI_ERROR_NPERMISSION = -1073807192;

const int VI_FIND_BUFLEN = 256;

const int VI_INTF_GPIB = 1;

const int VI_INTF_VXI = 2;

const int VI_INTF_GPIB_VXI = 3;

const int VI_INTF_ASRL = 4;

const int VI_INTF_PXI = 5;

const int VI_INTF_TCPIP = 6;

const int VI_INTF_USB = 7;

const int VI_PROT_NORMAL = 1;

const int VI_PROT_FDC = 2;

const int VI_PROT_HS488 = 3;

const int VI_PROT_4882_STRS = 4;

const int VI_PROT_USBTMC_VENDOR = 5;

const int VI_FDC_NORMAL = 1;

const int VI_FDC_STREAM = 2;

const int VI_LOCAL_SPACE = 0;

const int VI_A16_SPACE = 1;

const int VI_A24_SPACE = 2;

const int VI_A32_SPACE = 3;

const int VI_A64_SPACE = 4;

const int VI_PXI_ALLOC_SPACE = 9;

const int VI_PXI_CFG_SPACE = 10;

const int VI_PXI_BAR0_SPACE = 11;

const int VI_PXI_BAR1_SPACE = 12;

const int VI_PXI_BAR2_SPACE = 13;

const int VI_PXI_BAR3_SPACE = 14;

const int VI_PXI_BAR4_SPACE = 15;

const int VI_PXI_BAR5_SPACE = 16;

const int VI_OPAQUE_SPACE = 65535;

const int VI_UNKNOWN_LA = -1;

const int VI_UNKNOWN_SLOT = -1;

const int VI_UNKNOWN_LEVEL = -1;

const int VI_UNKNOWN_CHASSIS = -1;

const int VI_QUEUE = 1;

const int VI_HNDLR = 2;

const int VI_SUSPEND_HNDLR = 4;

const int VI_ALL_MECH = 65535;

const int VI_ANY_HNDLR = 0;

const int VI_TRIG_ALL = -2;

const int VI_TRIG_SW = -1;

const int VI_TRIG_TTL0 = 0;

const int VI_TRIG_TTL1 = 1;

const int VI_TRIG_TTL2 = 2;

const int VI_TRIG_TTL3 = 3;

const int VI_TRIG_TTL4 = 4;

const int VI_TRIG_TTL5 = 5;

const int VI_TRIG_TTL6 = 6;

const int VI_TRIG_TTL7 = 7;

const int VI_TRIG_ECL0 = 8;

const int VI_TRIG_ECL1 = 9;

const int VI_TRIG_ECL2 = 10;

const int VI_TRIG_ECL3 = 11;

const int VI_TRIG_ECL4 = 12;

const int VI_TRIG_ECL5 = 13;

const int VI_TRIG_STAR_SLOT1 = 14;

const int VI_TRIG_STAR_SLOT2 = 15;

const int VI_TRIG_STAR_SLOT3 = 16;

const int VI_TRIG_STAR_SLOT4 = 17;

const int VI_TRIG_STAR_SLOT5 = 18;

const int VI_TRIG_STAR_SLOT6 = 19;

const int VI_TRIG_STAR_SLOT7 = 20;

const int VI_TRIG_STAR_SLOT8 = 21;

const int VI_TRIG_STAR_SLOT9 = 22;

const int VI_TRIG_STAR_SLOT10 = 23;

const int VI_TRIG_STAR_SLOT11 = 24;

const int VI_TRIG_STAR_SLOT12 = 25;

const int VI_TRIG_STAR_INSTR = 26;

const int VI_TRIG_PANEL_IN = 27;

const int VI_TRIG_PANEL_OUT = 28;

const int VI_TRIG_STAR_VXI0 = 29;

const int VI_TRIG_STAR_VXI1 = 30;

const int VI_TRIG_STAR_VXI2 = 31;

const int VI_TRIG_TTL8 = 32;

const int VI_TRIG_TTL9 = 33;

const int VI_TRIG_TTL10 = 34;

const int VI_TRIG_TTL11 = 35;

const int VI_TRIG_PROT_DEFAULT = 0;

const int VI_TRIG_PROT_ON = 1;

const int VI_TRIG_PROT_OFF = 2;

const int VI_TRIG_PROT_SYNC = 5;

const int VI_TRIG_PROT_RESERVE = 6;

const int VI_TRIG_PROT_UNRESERVE = 7;

const int VI_READ_BUF = 1;

const int VI_WRITE_BUF = 2;

const int VI_READ_BUF_DISCARD = 4;

const int VI_WRITE_BUF_DISCARD = 8;

const int VI_IO_IN_BUF = 16;

const int VI_IO_OUT_BUF = 32;

const int VI_IO_IN_BUF_DISCARD = 64;

const int VI_IO_OUT_BUF_DISCARD = 128;

const int VI_FLUSH_ON_ACCESS = 1;

const int VI_FLUSH_WHEN_FULL = 2;

const int VI_FLUSH_DISABLE = 3;

const int VI_NMAPPED = 1;

const int VI_USE_OPERS = 2;

const int VI_DEREF_ADDR = 3;

const int VI_DEREF_ADDR_BYTE_SWAP = 4;

const int VI_TMO_IMMEDIATE = 0;

const int VI_TMO_INFINITE = 4294967295;

const int VI_NO_LOCK = 0;

const int VI_EXCLUSIVE_LOCK = 1;

const int VI_SHARED_LOCK = 2;

const int VI_LOAD_CONFIG = 4;

const int VI_NO_SEC_ADDR = 65535;

const int VI_ASRL_PAR_NONE = 0;

const int VI_ASRL_PAR_ODD = 1;

const int VI_ASRL_PAR_EVEN = 2;

const int VI_ASRL_PAR_MARK = 3;

const int VI_ASRL_PAR_SPACE = 4;

const int VI_ASRL_STOP_ONE = 10;

const int VI_ASRL_STOP_ONE5 = 15;

const int VI_ASRL_STOP_TWO = 20;

const int VI_ASRL_FLOW_NONE = 0;

const int VI_ASRL_FLOW_XON_XOFF = 1;

const int VI_ASRL_FLOW_RTS_CTS = 2;

const int VI_ASRL_FLOW_DTR_DSR = 4;

const int VI_ASRL_END_NONE = 0;

const int VI_ASRL_END_LAST_BIT = 1;

const int VI_ASRL_END_TERMCHAR = 2;

const int VI_ASRL_END_BREAK = 3;

const int VI_STATE_ASSERTED = 1;

const int VI_STATE_UNASSERTED = 0;

const int VI_STATE_UNKNOWN = -1;

const int VI_BIG_ENDIAN = 0;

const int VI_LITTLE_ENDIAN = 1;

const int VI_DATA_PRIV = 0;

const int VI_DATA_NPRIV = 1;

const int VI_PROG_PRIV = 2;

const int VI_PROG_NPRIV = 3;

const int VI_BLCK_PRIV = 4;

const int VI_BLCK_NPRIV = 5;

const int VI_D64_PRIV = 6;

const int VI_D64_NPRIV = 7;

const int VI_D64_2EVME = 8;

const int VI_D64_SST160 = 9;

const int VI_D64_SST267 = 10;

const int VI_D64_SST320 = 11;

const int VI_WIDTH_8 = 1;

const int VI_WIDTH_16 = 2;

const int VI_WIDTH_32 = 4;

const int VI_WIDTH_64 = 8;

const int VI_GPIB_REN_DEASSERT = 0;

const int VI_GPIB_REN_ASSERT = 1;

const int VI_GPIB_REN_DEASSERT_GTL = 2;

const int VI_GPIB_REN_ASSERT_ADDRESS = 3;

const int VI_GPIB_REN_ASSERT_LLO = 4;

const int VI_GPIB_REN_ASSERT_ADDRESS_LLO = 5;

const int VI_GPIB_REN_ADDRESS_GTL = 6;

const int VI_GPIB_ATN_DEASSERT = 0;

const int VI_GPIB_ATN_ASSERT = 1;

const int VI_GPIB_ATN_DEASSERT_HANDSHAKE = 2;

const int VI_GPIB_ATN_ASSERT_IMMEDIATE = 3;

const int VI_GPIB_HS488_DISABLED = 0;

const int VI_GPIB_HS488_NIMPL = -1;

const int VI_GPIB_UNADDRESSED = 0;

const int VI_GPIB_TALKER = 1;

const int VI_GPIB_LISTENER = 2;

const int VI_VXI_CMD16 = 512;

const int VI_VXI_CMD16_RESP16 = 514;

const int VI_VXI_RESP16 = 2;

const int VI_VXI_CMD32 = 1024;

const int VI_VXI_CMD32_RESP16 = 1026;

const int VI_VXI_CMD32_RESP32 = 1028;

const int VI_VXI_RESP32 = 4;

const int VI_ASSERT_SIGNAL = -1;

const int VI_ASSERT_USE_ASSIGNED = 0;

const int VI_ASSERT_IRQ1 = 1;

const int VI_ASSERT_IRQ2 = 2;

const int VI_ASSERT_IRQ3 = 3;

const int VI_ASSERT_IRQ4 = 4;

const int VI_ASSERT_IRQ5 = 5;

const int VI_ASSERT_IRQ6 = 6;

const int VI_ASSERT_IRQ7 = 7;

const int VI_UTIL_ASSERT_SYSRESET = 1;

const int VI_UTIL_ASSERT_SYSFAIL = 2;

const int VI_UTIL_DEASSERT_SYSFAIL = 3;

const int VI_VXI_CLASS_MEMORY = 0;

const int VI_VXI_CLASS_EXTENDED = 1;

const int VI_VXI_CLASS_MESSAGE = 2;

const int VI_VXI_CLASS_REGISTER = 3;

const int VI_VXI_CLASS_OTHER = 4;

const int VI_PXI_ADDR_NONE = 0;

const int VI_PXI_ADDR_MEM = 1;

const int VI_PXI_ADDR_IO = 2;

const int VI_PXI_ADDR_CFG = 3;

const int VI_TRIG_UNKNOWN = -1;

const int VI_PXI_LBUS_UNKNOWN = -1;

const int VI_PXI_LBUS_NONE = 0;

const int VI_PXI_LBUS_STAR_TRIG_BUS_0 = 1000;

const int VI_PXI_LBUS_STAR_TRIG_BUS_1 = 1001;

const int VI_PXI_LBUS_STAR_TRIG_BUS_2 = 1002;

const int VI_PXI_LBUS_STAR_TRIG_BUS_3 = 1003;

const int VI_PXI_LBUS_STAR_TRIG_BUS_4 = 1004;

const int VI_PXI_LBUS_STAR_TRIG_BUS_5 = 1005;

const int VI_PXI_LBUS_STAR_TRIG_BUS_6 = 1006;

const int VI_PXI_LBUS_STAR_TRIG_BUS_7 = 1007;

const int VI_PXI_LBUS_STAR_TRIG_BUS_8 = 1008;

const int VI_PXI_LBUS_STAR_TRIG_BUS_9 = 1009;

const int VI_PXI_STAR_TRIG_CONTROLLER = 1413;

const int VI_ERROR_INV_SESSION = -1073807346;

const int VI_INFINITE = 4294967295;

const int VI_NORMAL = 1;

const int VI_FDC = 2;

const int VI_HS488 = 3;

const int VI_ASRL488 = 4;

const int VI_ASRL_IN_BUF = 16;

const int VI_ASRL_OUT_BUF = 32;

const int VI_ASRL_IN_BUF_DISCARD = 64;

const int VI_ASRL_OUT_BUF_DISCARD = 128;

const int VI_ERROR_HW_NGENUINE = -1073807190;

const int VI_INTF_RIO = 8;

const int VI_INTF_FIREWIRE = 9;

const int VI_ATTR_SYNC_MXI_ALLOW_EN = 1073676641;

const int VI_EVENT_VXI_DEV_CMD = 3221168143;

const int VI_ATTR_VXI_DEV_CMD_TYPE = 1073692727;

const int VI_ATTR_VXI_DEV_CMD_VALUE = 1073692728;

const int VI_VXI_DEV_CMD_TYPE_16 = 16;

const int VI_VXI_DEV_CMD_TYPE_32 = 32;

const int VI_VXI_RESP_NONE = 0;

const int VI_VXI_RESP_PROT_ERROR = -1;

const int VI_ATTR_VXI_TRIG_LINES_EN = 1073692739;

const int VI_ATTR_VXI_TRIG_DIR = 1073692740;

const int VI_ATTR_ASRL_DISCARD_NULL = 1073676464;

const int VI_ATTR_ASRL_CONNECTED = 1073676731;

const int VI_ATTR_ASRL_BREAK_STATE = 1073676732;

const int VI_ATTR_ASRL_BREAK_LEN = 1073676733;

const int VI_ATTR_ASRL_ALLOW_TRANSMIT = 1073676734;

const int VI_ATTR_ASRL_WIRE_MODE = 1073676735;

const int VI_ASRL_WIRE_485_4 = 0;

const int VI_ASRL_WIRE_485_2_DTR_ECHO = 1;

const int VI_ASRL_WIRE_485_2_DTR_CTRL = 2;

const int VI_ASRL_WIRE_485_2_AUTO = 3;

const int VI_ASRL_WIRE_232_DTE = 128;

const int VI_ASRL_WIRE_232_DCE = 129;

const int VI_ASRL_WIRE_232_AUTO = 130;

const int VI_EVENT_ASRL_BREAK = 1073684515;

const int VI_EVENT_ASRL_CTS = 1073684521;

const int VI_EVENT_ASRL_DSR = 1073684522;

const int VI_EVENT_ASRL_DCD = 1073684524;

const int VI_EVENT_ASRL_RI = 1073684526;

const int VI_EVENT_ASRL_CHAR = 1073684533;

const int VI_EVENT_ASRL_TERMCHAR = 1073684516;

const int VI_ATTR_FIREWIRE_DEST_UPPER_OFFSET = 1073676784;

const int VI_ATTR_FIREWIRE_SRC_UPPER_OFFSET = 1073676785;

const int VI_ATTR_FIREWIRE_WIN_UPPER_OFFSET = 1073676786;

const int VI_ATTR_FIREWIRE_VENDOR_ID = 1073676787;

const int VI_ATTR_FIREWIRE_LOWER_CHIP_ID = 1073676788;

const int VI_ATTR_FIREWIRE_UPPER_CHIP_ID = 1073676789;

const int VI_FIREWIRE_DFLT_SPACE = 5;
